import React from 'react'
import Head from 'next/head'

const aboutus = () => {
	return (
		<>
			<Head>
				<title>spryDex - About Us</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon-white.png" />
			</Head>
		</>
	)
}

export default aboutus