import Head from 'next/head'
import { useEffect, useContext } from 'react'
import CryptoPanel from '../components/CryptoPanel'
import NewsPanel from '../components/NewsPanel'
import toast from 'react-hot-toast'
import { ThemeContext } from '../context/ThemeState'
import { ToastOptionsContext } from '../context/ToastOptionsState'
import { useSession } from 'next-auth/react'
import { SignedInContext } from '../context/SignedInState'

export default function Home() {
  const { theme } = useContext(ThemeContext)
  const { toastOptions } = useContext(ToastOptionsContext)
  const { signedIn, setSignedIn } = useContext(SignedInContext)

  const { data: session } = useSession()

  useEffect(() => {
    // console.log(session)
    if (!signedIn && session) {
      toast
        .success(
          'Signed In Successfully!',
          theme === 'light' ? toastOptions.light : toastOptions.dark
        )
      setSignedIn(true)
    }
  }, [session && session.user])

  return (
    <>
      <Head>
        <title>spryDex - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-white.png" />
      </Head>

      <div className="container mx-auto">
        <CryptoPanel />
        <hr />
        <NewsPanel />
      </div>
    </>
  )
}