import React, { useState, useContext } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { FcGoogle } from 'react-icons/fc'
import { BsFacebook, BsKeyFill } from 'react-icons/bs'
import { BiLogInCircle } from 'react-icons/bi'
import { IoCreateOutline } from 'react-icons/io5'
import { RiAccountCircleFill } from 'react-icons/ri'
import { HiMail } from 'react-icons/hi'
import { useSession, signIn, signOut } from 'next-auth/react'
import ForbiddenAccess from '../layouts/ForbiddenAccess'
import toast from 'react-hot-toast'
import { ToastOptionsContext } from '../context/ToastOptionsState'
import { ThemeContext } from '../context/ThemeState'

const login = () => {
	const { toastOptions } = useContext(ToastOptionsContext)
	const { theme } = useContext(ThemeContext)

	const [userCredentials, setUserCredentials] = useState({
		email: '', password: ''
	})

	const router = useRouter()

	const userLoginHandler = () => {
		console.log(userCredentials)

	}

	const googleSignInHandler = async () => {
		await signIn('google', { callbackUrl: 'http://localhost:3000' })

		// toast
		// 	.success(
		// 		'Signed In Successfully!',
		// 		theme === 'light' ? toastOptions.light : toastOptions.dark
		// 	)
		// router.push('/')
	}

	const onChange = (e) => {
		setUserCredentials({ ...userCredentials, [e.target.name]: e.target.value })
	}

	// google login session
	const { data: session } = useSession()

	if (session)
		return (
			<>
				<ForbiddenAccess />
				<div className="flex justify-center items-center space-x-2 text-3xl text-indigo-500 text-center font-medium">
					<RiAccountCircleFill />
					<h1 className='cursor-pointer' onClick={ () => { signOut() } }>LOG OUT</h1>
				</div>
			</>
		)

	return (
		<>
			<Head>
				<title>spryDex - Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon-white.png" />
			</Head>
			<div className="container mx-auto my-5 p-5">
				<div className="form bg-white shadow-xl rounded-lg mx-auto md:w-1/2">
					<div className="head w-full bg-indigo-500 flex justify-center items-center space-x-5 rounded-t-lg px-5 py-2">
						<Image src={ '/spryDEX-sym-white.png' } height={ '50' } width={ '50' } alt='spryDEX' />
						<h1 className='text-white text-3xl font-semibold'>spryDEX</h1>
					</div>

					<div className="body px-5 py-10 lg:w-1/2 mx-auto space-y-5">
						<div className="flex justify-center items-center space-x-2 text-3xl text-indigo-500 text-center font-medium">
							<RiAccountCircleFill />
							<h1 className=''>LOGIN</h1>
						</div>

						<div className="input-group flex items-center space-x-5 border border-gray-300 rounded text-lg bg-white px-2 py-1 focus-within:border-indigo-500 focus-within:ring-1 focus-within:ring-indigo-500 duration-200 ease-in-out">
							<label htmlFor="email" className="input-label">
								<HiMail className='text-lg' />
							</label>
							<input type="email" id='email' name='email' className='outline-none' placeholder='Email' onChange={ onChange } />
						</div>

						<div className="input-group flex items-center space-x-5 border border-gray-300 rounded text-lg bg-white px-2 py-1 focus-within:border-indigo-500 focus-within:ring-1 focus-within:ring-indigo-500 duration-200 ease-in-out">
							<label htmlFor="email" className="input-label">
								<BsKeyFill className='text-lg' />
							</label>
							<input type="password" id='password' name='password' className='outline-none' placeholder='Password' onChange={ onChange } />
						</div>

						<div className='text-center'>
							<span className='text-sm text-gray-400 cursor-pointer hover:text-gray-500'>Forgot Password?</span>
						</div>

						<button className='flex items-center space-x-3 mx-auto text-white bg-indigo-500 border-0 py-2 px-10 focus:outline-none hover:bg-indigo-600 rounded text-lg my-4' onClick={ userLoginHandler }>
							<span>Login</span>
							<span><BiLogInCircle /></span>
						</button>

						<div className='text-center'>
							<span className='text-center text-gray-500'>or</span>
						</div>

						<div className='text-center'>
							<span>Sign In With</span>

							<div className='flex space-x-5 justify-center text-4xl mt-1'>
								<button className='hover:bg-slate-100 rounded-full p-2 duration-100' onClick={ googleSignInHandler }>
									<FcGoogle className='cursor-pointer' />
								</button>
								<button className='hover:bg-slate-100 rounded-full p-2 duration-100'>
									<BsFacebook className='cursor-pointer text-facebook' />
								</button>
							</div>
						</div>

						<hr />

						<div className="text-center">
							<span>Don't Have an Account?</span>
						</div>

						<Link href={ '/signup' }>
							<button className='flex items-center space-x-3 mx-auto text-white bg-indigo-500 border-0 py-2 px-10 focus:outline-none hover:bg-indigo-600 rounded text-lg my-4'>
								<span>Sign Up</span>
								<span><IoCreateOutline /></span>
							</button>
						</Link>
					</div>
				</div>
			</div>
		</>
	)
}

export default login