import React from 'react'
import Head from 'next/head'

const news = () => {
	return (
		<>
			<Head>
				<title>spryDex - News</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon-white.png" />
			</Head>
			news
		</>
	)
}

export default news