import React from 'react'
import Head from 'next/head'
import HorizontalNews from '../layouts/HorizontalNews'

const news = () => {
	return (
		<>
			<Head>
				<title>spryDex - News</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon-white.png" />
			</Head>
			<div className='mx-2 md:mx-10 py-10 flex justify-between items-center flex-wrap'>
				<HorizontalNews />
			</div>
		</>
	)
}

export default news