import React, { useEffect, useState } from 'react'
import Image from 'next/image'
import Head from 'next/head'
import { useRouter } from 'next/router'

const ForbiddenAccess = () => {
	const router = useRouter()

	const [redirectTime, setRedirectTime] = useState(5)

	const redirect = () => {
		redirectTime === 1 && router.push('/')
		setRedirectTime(redirectTime - 1)
	}

	useEffect(() => {
		setTimeout(() => {
			redirect()
		}, 1000);
	}, [redirectTime])

	return (
		<>
			<Head>
				<title>spryDex - FORBIDDEN ACCESS!</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon-white.png" />
			</Head>

			<div className="flex flex-col justify-center items-center py-10">
				<h1 className='my-5 text-5xl font-semibold animate-pulse text-red-500 tracking-wide'>FORBIDDEN ACCESS!</h1>
				<Image src={ '/unauth_access_403.png' } width={ 500 } height={ 300 } className='bg-white my-5 rounded-lg shadow-2xl' />
				<p className='my-5 text-2xl'>We are sorry, but you do not have access to this page or resource.</p>

				<h3 className='text-xl text-slate-500'>
					<span>Redirecting you to Home in </span>
					<span className='font-semibold'>{ redirectTime }</span>
					<span> sec</span>
				</h3>
			</div>
		</>
	)
}

export default ForbiddenAccess